services:

  server_services:
    build: ./server
    container_name: server_services
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"


  client_services:
    build: 
      context: ./client
      args:
        VITE_APP_API_URL: http://40.192.99.158:3000/api
    container_name: client_services
  
    ports:
      - "4000:4000"
    depends_on:
      - server_services

